### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by valentinomario** [TheFox/keylogger#4]
\keylogger-master\src\collect2.exe  [Error] ld returned 1 exit status

**Comment by TheFox** [comment]
Such a short issue ticket is not very helpful to reproduce this error.
- What OS do you use?
- What IDE do you use?
- What Compiler do you use?
- Which commands has been execucted do start the build process?

**Comment by valentinomario** [comment]
ok,i'm on windows 8.1 with Dev C++ and to start the execution i'v just clicked on "compile and run button"

**Comment by valentinomario** [comment]
**Update**
the 32 string in main became red for the error: 
string basepath = dirBasename(getSelfPath());

**Comment by TheFox** [comment]
Do you have more information about this error?

**Comment by valentinomario** [comment]
Sorry the Fox it was an error of my computer.
There was a bug in c++ runtime library so I formatted the computer and now is working great 
Thanks however!!
